apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

# namespace: gabsns
images:
- name: goserver
  newName: gabsferrara/gitopspoc
  newTag: ce5e718a7becdaab539d7a6d3247ae4d511a5162
